# Configuration file for ctf-service
# Services are listed here in "[[Service]] sections"
# Key value pairs go in each section

# Fill out this service section to get started
# Add more as needed
[[Service]]
# Simple name for the service
name=

# Path to the program to execute
filepath=

# Only the executable type is supported currently
type=executable

# Listen port for the service
port=

# At least one addr or addr6 key is required
# There can be multiple of each per service
addr=
#addr6=

